# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
cache: packages

before_install:
  - Rscript -e 'install.packages("remotes")'
  - Rscript -e 'remotes::install_github("cwida/duckdb/tools/rpkg", build = FALSE)'
after_success:
  - Rscript -e 'covr::codecov()'

